const CHAIRMANS = 0;
const CHAIRMANS_FINALIST = 69;
const WINNER = 1;
const WOODIE_FLOWERS = 3;
const SKILLS_COMPETITION_WINNER = 74;
const GAME_DESIGN_CHALLENGE_WINNER = 80;

export function isBlueBannerAward(awardType: number): boolean {
	return [CHAIRMANS, CHAIRMANS_FINALIST, WINNER, WOODIE_FLOWERS, SKILLS_COMPETITION_WINNER, GAME_DESIGN_CHALLENGE_WINNER].includes(awardType);
}
